# Generated by Django 4.1.5 on 2023-01-24 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_meds', to='products.products')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_meds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
