# Generated by Django 4.1.5 on 2023-01-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_category'),
        ('my_meds', '0002_rename_medications_mymeds_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymeds',
            name='products',
        ),
        migrations.AddField(
            model_name='mymeds',
            name='products',
            field=models.ManyToManyField(related_name='my_meds', to='products.products'),
        ),
    ]
