# Generated by Django 4.1.5 on 2023-01-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
