# Generated by Django 4.1.5 on 2023-01-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_requests_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='done',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
