# Generated by Django 4.1.5 on 2023-01-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_requests_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='done',
        ),
    ]
