# Generated by Django 4.1.5 on 2023-01-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dose', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=3)),
                ('image', models.CharField(max_length=400)),
                ('form', models.CharField(max_length=75)),
                ('interactions', models.CharField(max_length=300)),
                ('side_effects', models.CharField(max_length=300)),
                ('drive', models.BooleanField()),
                ('food', models.BooleanField()),
                ('primary_use', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=2000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brand.brand')),
            ],
        ),
    ]
