# Generated by Django 4.1.5 on 2023-01-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='drive',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='food',
            field=models.CharField(max_length=10),
        ),
    ]
