# Generated by Django 4.1.5 on 2023-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_drive_alter_products_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='drive',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='food',
            field=models.BooleanField(),
        ),
    ]
